# Generated by Django 3.1.3 on 2020-12-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='paid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
