# Generated by Django 3.1.3 on 2020-12-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_loan_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='paid',
            field=models.FloatField(default=0),
        ),
    ]
