# Generated by Django 3.1.3 on 2020-11-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='has_fine',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
