# Generated by Django 3.1.3 on 2020-12-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20201221_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='fine_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
