# Generated by Django 3.1.3 on 2020-12-21 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0005_auto_20201221_1500'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('status', models.CharField(default='Active', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('is_member', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('ref_number', models.CharField(blank=True, max_length=100, null=True)),
                ('sirname', models.CharField(blank=True, max_length=100, null=True)),
                ('profile', models.ImageField(default='/images/default/profile/logo.png', upload_to='images/users')),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
        ),
    ]
