# Generated by Django 3.1.3 on 2020-11-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201118_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='profile',
            field=models.ImageField(default='/images/default/profile/logo.png', upload_to='images/users'),
        ),
    ]
