# Generated by Django 3.0.3 on 2020-06-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200625_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(blank=True, default='images/users/default/brand.png', null=True, upload_to='images/users'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(default='Active', max_length=5),
        ),
    ]
