# Generated by Django 3.1.3 on 2020-11-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_team_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
