# Generated by Django 3.1.3 on 2020-12-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
