# Generated by Django 3.1.3 on 2020-12-31 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_member_fine_count'),
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hisa_amount', models.FloatField(blank=True, default=0, null=True)),
                ('jamii_amount', models.FloatField(blank=True, default=0, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='member.member')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='share.weekmodel')),
            ],
        ),
    ]
